server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/public/thymeleaf/
    cache: false
  devtools:
    restart:
      exclude: com.adamzfc.domain.model
  jpa:
    hibernate:
      ddl-auto: validate

mybatis:
  type-aliases-package: com.adamzfc.domain.model
  configuration:
    use-actual-param-name: true

mapper:
  mappers: com.adamzfc.infrastructure.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
flyway:
  baseline-on-migrate: true
  url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&serverTimezone=UTC
  user: root
  password: 123456
  locations: db/migration
  enabled: true
debug: true

