server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/public/thymeleaf/
    cache: false
  devtools:
    restart:
      exclude: com.adamzfc.domain.model
mybatis:
  type-aliases-package: com.adamzfc.domain.model
mapper:
  mappers: com.adamzfc.infrastructure.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

